language: objective-c
osx_image: xcode9.1
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "NavigationBarHelper.xcodeproj" -scheme "NavigationBarHelper" -configuration Debug ONLY_ACTIVE_ARCH=NO build
